-- change stock after insert on order
CREATE OR REPLACE TRIGGER UPDATE_STOCK
AFTER INSERT
ON ORDER_TABLE
FOR EACH ROW
DECLARE
    CID NUMBER;
    BID NUMBER;
    AMNT NUMBER;
BEGIN
    CID := :NEW.CART_ID;
    FOR R in (SELECT * FROM ROKOMARI.PICKED p WHERE p.CART_ID =CID)
    LOOP
        BID := R.BOOK_ID;
        AMNT := R.AMOUNT;
        UPDATE ROKOMARI.BOOK b SET b.STOCK  = STOCK - AMNT WHERE b.BOOK_ID  = BID;
    END LOOP;
END;